apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      annotations: null
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: 'public.ecr.aws/bitnami/nginx:1.25.3'
          resources:
            limits:
              cpu: '1'
              ephemeral-storage: 64Mi
              memory: 256Mi
            requests:
              cpu: '0.1'
              ephemeral-storage: 64Mi
              memory: 64Mi
